version: '3.4'

services:
  helloweb1:
    image: fring02/hellowebapps:helloweb1
    environment:
      - "Response:Text=Привет, Астана"
    ports:
      - "4000:80"

  helloweb2:
    image: fring02/hellowebapps:helloweb1
    environment:
      - "Response:Text=Привет, Алматы"
    ports:
      - "4001:80"  

  helloweb3:
    image: fring02/hellowebapps:helloweb1
    environment:
      - "Response:Text=Привет, Ақтөбе"
    ports:
      - "4002:80"